! BEGIN DART PREPROCESS KIND LIST
!TEMPERATURE,  QTY_PFLOTRAN_TEMPERATURE, COMMON_CODE
!PERMEABILITY,  QTY_PFLOTRAN_PERMEABILITY, COMMON_CODE
!POROSITY,  QTY_PFLOTRAN_POROSITY, COMMON_CODE
!THERMALCONDUCTIVITY,  QTY_PFLOTRAN_THERMALCONDUCTIVITY, COMMON_CODE
! END DART PREPROCESS KIND LIST
