! BEGIN DART PREPROCESS KIND LIST
!TEMPERATURE,  QTY_PFLOTRAN_TEMPERATURE, COMMON_CODE
!FLOWFLUX,  QTY_PFLOTRAN_FLOWFLUX, COMMON_CODE
!POROSITY,  QTY_PFLOTRAN_POROSITY, COMMON_CODE
!THERMALCONDUCTIVITY,  QTY_PFLOTRAN_THERMALCONDUCTIVITY, COMMON_CODE
! END DART PREPROCESS KIND LIST
