! BEGIN DART PREPROCESS KIND LIST
!TEMPERATURE,  QTY_PFLOTRAN_TEMPERATURE, COMMON_CODE
!PERMEABILITY,  QTY_PFLOTRAN_PERMEABILITY, COMMON_CODE
!POROSITY,  QTY_PFLOTRAN_POROSITY, COMMON_CODE
!THERMALCONDUCTIVITY,  QTY_PFLOTRAN_THERMALCONDUCTIVITY, COMMON_CODE
!LIQUID_SATURATION,  QTY_PFLOTRAN_LIQUID_SATURATION, COMMON_CODE
!LIQUID_PRESSURE,  QTY_PFLOTRAN_LIQUID_PRESSURE, COMMON_CODE
!TEST_VARIABLE,  QTY_PFLOTRAN_TEST_VARIABLE, COMMON_CODE
!TEST_VARIABLEAAA,  QTY_PFLOTRAN_TEST_VARIABLEAAA, COMMON_CODE
! END DART PREPROCESS KIND LIST
